
type Account = {
    name: string,
    username: string,
    password: string,
    token: string,
    phId: string,
    phType: string,
    phManufacturer: string,
    phModel: string,
    phProduct: string
}

export const getAccount = (username: string):Account|null => {
    const accounts:Account[] = [
        {
            name:"AHMAD KHAIRUN ARSYAD",
            username: "199710262023211003",
            password: "",
            token: "df491591ummrle8v912vvmbdcbnrmmom",
            phId: "49b956bf737edce5",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "24069PC21G",
            phProduct: "peridot_global",
        },
        {
            name:"RIEVKY ARDIKA PUTRA, S.Kom",
            username: "199012072022031003",
            password: "",
            token: "df491591ummrle8v912vvmbdcbnrmmom",
            phId: "605484158e9b96c0",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "22021211RG",
            phProduct: "munch_id",
        },
        {
            name:"SURIPTO, S.Kom.",
            username: "199209242023211016",
            password: "",
            token: "7na6u3bvc8ei77fgdh7u2ahg0j169fjk",
            phId: "2ce92207806d77a8",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-M325FV",
            phProduct: "m32xx",
        },
        {
            name:"DANANG TRISDIANA PUTRA, S.Kom.",
            username: "199804112024211004",
            password: "",
            token: "7h4gsbcatf1v84ul5aalsp2qk17rpauc",
            phId: "97644af1e96963b5",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "22071212AG",
            phProduct: "plato_id",
        },
        {
            name:"DENI PRIYANTO, SST",
            username: "198512112024211006",
            password: "",
            token: "7h4gsbcatf1v84ul5aalsp2qk17rpauc",
            phId: "a7a3061692d16478",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-A515F",
            phProduct: "a51nsxx",
        },
        {
            name:"MOCHAMAD SYENA BACHARUDIN, S.Kom",
            username: "199110252025061001",
            password: "",
            token: "7h4gsbcatf1v84ul5aalsp2qk17rpauc",
            phId: "6f7df1b1bcbc4652",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-G998B",
            phProduct: "p3sxxx",
        },
        {
            name:"ANITA SRI HANDAYANI, S.Kom",
            username: "199511262024212030",
            password: "",
            token: "",
            phId: "cb486201fef4e32c",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "M2004J19C",
            phProduct: "lancelot_id",
        },
        {
            name:"ATIM MUFARRIHAH, S.Kom.",
            username: "199106192020122005",
            password: "",
            token: "",
            phId: "b3d651f5b64ba7bf",
            phType: "GSM",
            phManufacturer: "INFINIX",
            phModel: "Infinix X6882",
            phProduct: "X6882-OP",
        },
        {
            name:"M. RIDWAN HANAFI, S.Kom.",
            username: "199301182018011003",
            password: "",
            token: "",
            phId: "5047db03f8e0e629",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-A566B",
            phProduct: "a56xnaxx",
        },
        {
            name:"SWANDI",
            username: "198604222010011013",
            password: "",
            token: "",
            phId: "35217c95b2c44767",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "2407FPN8EG",
            phProduct: "rothko_global",
        },
        {
            name:"DANU",
            username: "199712172022031003",
            password: "",
            token: "",
            phId: "8735aaed2b6fc877",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-S711B",
            phProduct: "r11sxxx",
        },
        {
            name:"Novel",
            username: "199707092023211003",
            password: "",
            token: "",
            phId: "ee0a98a2140b6e1c",
            phType: "GSM",
            phManufacturer: "Xiaomi",
            phModel: "2310FPCA4G",
            phProduct: "gust_p_id",
        },
        {
            name:"Fatin",
            username: "199710272022031003",
            password: "",
            token: "",
            phId: "aecf93cda517a087",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-A515F",
            phProduct: "a51nsxx",
        },
        {
            name:"Yaya",
            username: "199410292022032006",
            password: "",
            token: "",
            phId: "b60c8c222a1ab94b",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-S921B",
            phProduct: "e1sxxx",
        },
        {
            name:"Gunawan",
            username: "199008102020121006",
            password: "",
            token: "",
            phId: "3c29799a1a86ef45",
            phType: "GSM",
            phManufacturer: "OPPO",
            phModel: "CPH2669",
            phProduct: "CPH2669",
        },
        {
            name:"Anang",
            username: "197302121999021001",
            password: "",
            token: "",
            phId: "5e22d9e2e54eed03",
            phType: "GSM",
            phManufacturer: "samsung",
            phModel: "SM-A225F",
            phProduct: "a22nnxx",
        },

        
        // {
        //     name:"",
        //     username: "",
        //     password: "",
        //     token: "",
        //     phId: "",
        //     phType: "GSM",
        //     phManufacturer: "",
        //     phModel: "",
        //     phProduct: "",
        // },
    ]

    for(let i = 0; i < accounts.length; i++){
        if(accounts[i].username == username){
            return accounts[i]
        }
    }
    return null
}